[package]
name = "<CRATE_NAME>"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]
name = "mylib"

[dependencies]
uniffi = "0.23"
