[package]
name = "cargo-swift"
description = "A cargo plugin to easily build Swift packages from Rust code for use in iOS and macOS applications"
version = "0.2.1"
edition = "2021"
authors = ["Antonius Naumann <git@antonius.dev>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/antoniusnaumann/cargo-swift"
keywords = ["macos", "ios", "mobiledev", "spm", "swiftpackage"]
categories = ["command-line-utilities", "development-tools", "development-tools::build-utils", "development-tools::cargo-plugins", "development-tools::ffi"]
exclude = ["/readme", "/.github"]

[dependencies]
cargo_toml = "0.14.0"
clap = { version = "4.1.1", features = ["derive"] }
convert_case = "0.6.0"
dialoguer = { version = "0.10.3", default-features = false }
execute = "0.2.11"
indicatif = "0.17.3"
serde = { version = "1.0.152", features = ["derive"] }

swift-bridge-build = "0.1.49"
# Local version for checking integration with local swift-bridge-build changes
#  swift-bridge-build = { path = "../swift-bridge/crates/swift-bridge-build" }
