[package]
name = "cargo-swift"
description = "A cargo plugin to easily build Swift packages from Rust code for use in iOS and macOS applications"
version = "0.4.0"
edition = "2021"
authors = ["Antonius Naumann <git@antonius.dev>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/antoniusnaumann/cargo-swift"
keywords = ["macos", "ios", "uniffi", "spm", "swift"]
categories = ["command-line-utilities", "development-tools", "development-tools::build-utils", "development-tools::cargo-plugins", "development-tools::ffi"]
exclude = ["/readme", "/.github", "/testing"]

[dependencies]
camino = "1.1.6"
cargo_toml = "0.15.3"
clap = { version = "4.3.19", features = ["derive"] }
convert_case = "0.6.0"
serde = { version = "1.0.180", features = ["derive"] }
regex = "1.9.1"

# Terminal UI
dialoguer = { version = "0.10.4", default-features = false }
execute = "0.2.12"
indicatif = "0.17.6"

# FFI Bindings
uniffi_bindgen = "0.24.3"

# Error Handling
anyhow = "1.0.72"
thiserror = "1.0.44"
