[package]
name = "cargo-swift"
description = "A cargo plugin to easily build Swift packages from Rust code for use in iOS and macOS applications"
version = "0.2.2"
edition = "2021"
authors = ["Antonius Naumann <git@antonius.dev>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/antoniusnaumann/cargo-swift"
keywords = ["macos", "ios", "mobiledev", "spm", "swiftpackage"]
categories = ["command-line-utilities", "development-tools", "development-tools::build-utils", "development-tools::cargo-plugins", "development-tools::ffi"]
exclude = ["/readme", "/.github", "/testing"]

[dependencies]
camino = "1.1.4"
cargo_toml = "0.15.2"
clap = { version = "4.1.11", features = ["derive"] }
convert_case = "0.6.0"
serde = { version = "1.0.158", features = ["derive"] }
regex = "1.7.1"

# Terminal UI
dialoguer = { version = "0.10.3", default-features = false }
execute = "0.2.11"
indicatif = "0.17.3"

# FFI Bindings
uniffi_bindgen = "0.23.0"

# Error Handling
anyhow = "1.0.70"
thiserror = "1.0.40"
